enum UserActionsEnums {
  depositsAction,
  withdrawalsAction,
  transfersAction,
  showAccountBalance,
  showLogAction,
  showHisLogAction,
  showAllAccountsInformationAction,
  showHisAccountInformationAction,
  loginAction,
  createNewAccountAction,
  registeredAction,
  shutdownSystemAction,
  logoutAction,
}
